package CollectionOfFunctionalMethods.DatabaseRelatedMethods;
import java.sql.SQLException;

public class DatabaseDataOperation {
    public  String PRIMARYKEYID=null;
    public  String PLATFORM_DOMAIN_NAME="";
    public  String PLATFORM_EXCEPTION_INFORMATIN="调试";
    public  int PLATFORM_EXCEPTION_TYPE=0;
    public  int PLATFORM_STATUS=0;
    public  int NUMBEROFORDETRANSACTIONS=0;
    public  String CREATEIME=null;
    public  String PLATFORM_NAME=null;

    /**
     *
     * @param TYPE   数据类型
     * @param STATUS  数据状态
     * @param DOMIAN_NAME  平台域名
     * @param PLATFORM_NAME_DELEVER  平台域名
     * @param NUMBEROFORDETRANSACTIONSDELEVER   异常情况
     * @param CREATEIMEDELEVER 创建者
     * @param EXCEPTION_INFORMATIN  异常信息
     * @return
     * @throws SQLException
     */
    public String DataToInsertAbnormal(int TYPE,int STATUS,String DOMIAN_NAME,String PLATFORM_NAME_DELEVER ,int NUMBEROFORDETRANSACTIONSDELEVER,String CREATEIMEDELEVER,String EXCEPTION_INFORMATIN) throws SQLException {
        PLATFORM_STATUS=STATUS;
        PLATFORM_EXCEPTION_TYPE=TYPE;
        PLATFORM_EXCEPTION_INFORMATIN=EXCEPTION_INFORMATIN;
        PLATFORM_DOMAIN_NAME=DOMIAN_NAME;
        CREATEIME=CREATEIMEDELEVER;
        PLATFORM_NAME=PLATFORM_NAME_DELEVER;
        NUMBEROFORDETRANSACTIONS=NUMBEROFORDETRANSACTIONSDELEVER;
        String  sql="INSERT INTO `macaca`.`platform_exception_informatin_table`(`EXCEPTION_PRIMARY_KEY_ID`, `PLATFORM_DOMAIN_NAME`, `PLATFORM_NAME`,  `ARTSAN_NAME`, `PLATFORM_EXCEPTION_INFORMATIN`, `NUMBEROFORDETRANSACTIONS`, `PLATFORM_EXCEPTION_TYPE`, `PLATFORM_STATUS`,`CREATEIME`)"
                +"VALUES ("+PRIMARYKEYID+", '"+PLATFORM_DOMAIN_NAME+"', '"+PLATFORM_NAME+"', '吴正彪','"+PLATFORM_EXCEPTION_INFORMATIN+"',"+NUMBEROFORDETRANSACTIONS+","+PLATFORM_EXCEPTION_TYPE+","+PLATFORM_STATUS+",'"+CREATEIME+"');";
        System.out.print("insert sql："+sql);
        return sql;
    }
    public String DataToInsertStatictics(String DATAS_STATISTICS_DOMAIN_NAME ,String PLATFORM_NAME_DELEVER,int DATAS_STATISTICS_NUMBER,String CREATEIMEDELEVER,String DATAS_STATISTICS_EXCEPTION_INFORMATIN) throws SQLException {
        PLATFORM_EXCEPTION_INFORMATIN=DATAS_STATISTICS_EXCEPTION_INFORMATIN;
        PLATFORM_DOMAIN_NAME=DATAS_STATISTICS_DOMAIN_NAME;
        CREATEIME=CREATEIMEDELEVER;
        PLATFORM_NAME=PLATFORM_NAME_DELEVER;
        NUMBEROFORDETRANSACTIONS=DATAS_STATISTICS_NUMBER;
        String  sql="INSERT INTO `macaca`.`datas_statistics_query_table`(`DATAS_STATISTICS_KEY_ID`, `DATAS_STATISTICS_DOMAIN_NAME`, `PLATFORM_NAME`,  `ARTSAN_NAME`, `DATAS_STATISTICS_EXCEPTION_INFORMATIN`, `DATAS_STATISTICS_NUMBER`, `DATAS_STATISTICS_STATUS`,`CREATEIME`)"
                +"VALUES ("+PRIMARYKEYID+", '"+PLATFORM_DOMAIN_NAME+"', '"+PLATFORM_NAME+"', '吴正彪','"+PLATFORM_EXCEPTION_INFORMATIN+"',"+NUMBEROFORDETRANSACTIONS+","+0+",'"+CREATEIME+"');";
        System.out.print("insert sql："+sql);
        return sql;
    }

}
